CREATE DATABASE Group3_ETL_METADATA
GO

USE Group3_ETL_METADATA
GO 

/*
GO
USE MASTER
DROP DATABASE Group3_ETL_METADATA
GO

-- DROP TABLE
DROP TABLE DATA_FLOW
*/

CREATE TABLE DATA_FLOW(
	ID INT NOT NULL IDENTITY(1,1),
	TableName VARCHAR(20) NOT NULL,
	LSET DATETIME,
	CET DATETIME,
	CONSTRAINT PK_Data_Flow PRIMARY KEY CLUSTERED (ID)
)
go

SELECT * FROM DATA_FLOW
/*CREATE TRIGGER insert_dataflow on DATA_FLOW AFTER INSERT AS
BEGIN
	UPDATE DATA_FLOW
	SET LSET = GETDATE(), CET = GETDATE()
	WHERE ID IN (SELECT DISTINCT ID FROM INSERTED)
END
go*/

INSERT DATA_FLOW (TableName, LSET, CET) VALUES ('HocSinh_NDS', GETDATE(), GETDATE())
INSERT DATA_FLOW (TableName, LSET, CET) VALUES ('LopHoc_NDS', GETDATE(), GETDATE())
INSERT DATA_FLOW (TableName, LSET, CET) VALUES ('MonHoc_NDS', GETDATE(), GETDATE())
INSERT DATA_FLOW (TableName, LSET, CET) VALUES ('Diem_NDS', GETDATE(), GETDATE())
go


