CREATE DATABASE Group3_ETL_NDS
GO

USE Group3_ETL_NDS
GO 

/*
GO
USE MASTER
DROP DATABASE Group3_ETL_NDS
GO

-- DROP TABLE
GO
USE MASTER
DROP TABLE LopHoc_NDS
DROP TABLE HocSinh_NDS
DROP TABLE MonHoc_NDS
DROP TABLE Diem_NDS*/

-- Tạo bảng LopHoc_NDS 

CREATE TABLE LopHoc_NDS (
    MaLop_SK INT IDENTITY(1,1) PRIMARY KEY,
    MaLop_NK NVARCHAR(50) NOT NULL,
    TenLop NVARCHAR(255) NOT NULL,
    SiSo INT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedDate DATETIME NULL
);

-- Tạo bảng HocSinh_NDS
CREATE TABLE HocSinh_NDS (
    MaHS_SK INT IDENTITY(1,1) PRIMARY KEY,
    MaHS_NK NVARCHAR(50) NOT NULL,
    HoVaTen NVARCHAR(255) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh NVARCHAR(10) CHECK (GioiTinh IN ('Nam', 'Nữ')) NOT NULL,
    MaLop_SK INT NOT NULL REFERENCES LopHoc_NDS(MaLop_SK),
    Create_day DATETIME NOT NULL DEFAULT GETDATE(),
    Update_day DATETIME NULL
);

-- Tạo bảng MonHoc_NDS
CREATE TABLE MonHoc_NDS (
    MaMH_SK INT IDENTITY(1,1) PRIMARY KEY,
    MaMH_NK NVARCHAR(50) NOT NULL,
    TenMH NVARCHAR(255) NOT NULL,
    SoTC INT NOT NULL,
    Create_day DATETIME NOT NULL DEFAULT GETDATE(),
    Update_day DATETIME NULL
);

-- Tạo bảng Diem_NDS
CREATE TABLE Diem_NDS (
    MaHS_SK INT NOT NULL REFERENCES HocSinh_NDS(MaHS_SK),
    MaMH_SK INT NOT NULL REFERENCES MonHoc_NDS(MaMH_SK),
    Diem DECIMAL(5, 2) CHECK (Diem >= 0 AND Diem <= 10) NOT NULL,
    Create_day DATETIME NOT NULL DEFAULT GETDATE(),
    Update_day DATETIME NULL,
    PRIMARY KEY (MaHS_SK, MaMH_SK)
);

UPDATE LopHoc_NDS
SET siso = (
    SELECT COUNT(*)
    FROM HocSinh_NDS
    WHERE HocSinh_NDS.MaLop_SK = LopHoc_NDS.MaLop_SK
);
go

SELECT * FROM LopHoc_NDS;
SELECT * FROM HocSinh_NDS;
